#!/usr/bin/env bash 

mkdir -p ~/.config/nvim/plugin
mkdir -p ~/.config/nvim/after/plugin
mkdir -p ~/.config/nvim/lua

# link wholesale
for f in `find . -regex ".*\.vim$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/workspace/github/pattenp/dotfiles/$f ~/.config/nvim/$f
done

for f in `find . -regex ".*\.lua$"`; do
    rm -rf ~/.config/nvim/$f
    ln -s ~/workspace/github/pattenp/dotfiles/$f ~/.config/nvim/$f
done

#CoC
rm ~/.config/nvim/coc-settings.json
ln -s ~workspace/github/pattenp/dotfiles ~/.config/nvim/coc-settings.json

